[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --port /dev/cu.usbmodem2101 --non-interactive --skip-update-check"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
